/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application. For more information please */
/*  refer to the GUIX Studio user's guide, or visit our web site at            */
/*  www.expresslogic.com.                                                      */
/*                                                                             */
/*  GUIX Studio Revision 5.4.1.1                                               */
/*  Date (dd.mm.yyyy):  4.10.2018   Time (hh:mm): 09:27                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "audio_player_resources.h"
#include "audio_player_specifications.h"

W_BG_SPLASH_CONTROL_BLOCK w_bg_splash;
W_BG_USB_CONTROL_BLOCK w_bg_usb;
W_BG_MAIN_CONTROL_BLOCK w_bg_main;
static GX_WIDGET *gx_studio_nested_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent);


GX_DISPLAY display_1_control_block;
GX_CANVAS  display_1_canvas_control_block;
GX_WINDOW_ROOT display_1_root_window;

UINT gx_studio_pixelmap_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_PIXELMAP_BUTTON *button = (GX_PIXELMAP_BUTTON *) control_block;
    GX_PIXELMAP_BUTTON_PROPERTIES *props = (GX_PIXELMAP_BUTTON_PROPERTIES *) info->properties;
    status = gx_pixelmap_button_create(button, info->widget_name, parent,
               props->normal_pixelmap_id,
               props->selected_pixelmap_id,
               props->disabled_pixelmap_id,
               info->style, info->widget_id, &info->size);
    return status;
}

UINT gx_studio_icon_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_ICON *icon = (GX_ICON *) control_block;
    GX_ICON_PROPERTIES *props = (GX_ICON_PROPERTIES *) info->properties;
    status = gx_icon_create(icon, info->widget_name, parent, props->normal_pixelmap_id, info->style, info->widget_id, info->size.gx_rectangle_left, info->size.gx_rectangle_top);
    if (props->selected_pixelmap_id)
    {
        gx_icon_pixelmap_set(icon, props->normal_pixelmap_id, props->selected_pixelmap_id);
    }
    return status;
}

UINT gx_studio_progress_bar_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_PROGRESS_BAR *bar = (GX_PROGRESS_BAR *) control_block;
    GX_PROGRESS_BAR_INFO *bar_info = (GX_PROGRESS_BAR_INFO *) info->properties;
    status = gx_progress_bar_create(bar,
                    info->widget_name,
                    parent,
                    bar_info,
                    info->style,
                    info->widget_id,
                    &info->size);
    return status;
}

UINT gx_studio_sprite_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_SPRITE *sprite = (GX_SPRITE *) control_block;
    GX_SPRITE_PROPERTIES *props = (GX_SPRITE_PROPERTIES *) info->properties;
    status = gx_sprite_create(sprite, info->widget_name, parent,
               props->frame_list, props->frame_count,
               info->style, info->widget_id, &info->size);
    return status;
}

UINT gx_studio_prompt_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_PROMPT *prompt = (GX_PROMPT *) control_block;
    GX_PROMPT_PROPERTIES *props = (GX_PROMPT_PROPERTIES *) info->properties;
    status = gx_prompt_create(prompt, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_prompt_font_set(prompt, props->font_id);
        gx_prompt_text_color_set(prompt, props->normal_text_color_id, props->selected_text_color_id);
    }
    return status;
}

UINT gx_studio_window_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_WINDOW *window = (GX_WINDOW *) control_block;
    GX_WINDOW_PROPERTIES *props = (GX_WINDOW_PROPERTIES *) info->properties;
    status = gx_window_create(window, info->widget_name, parent, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        if (props->wallpaper_id)
        {
            gx_window_wallpaper_set(window, props->wallpaper_id, info->style & GX_STYLE_TILE_WALLPAPER);
        }
    }
    return status;
}

UINT gx_studio_vertical_list_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_VERTICAL_LIST *list = (GX_VERTICAL_LIST *) control_block;
    GX_VERTICAL_LIST_PROPERTIES *props = (GX_VERTICAL_LIST_PROPERTIES *) info->properties;
    status = gx_vertical_list_create(list, info->widget_name, parent, props->total_rows,
                                     props->callback, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        if (props->wallpaper_id)
        {
            gx_window_wallpaper_set((GX_WINDOW *) list, props->wallpaper_id, info->style & GX_STYLE_TILE_WALLPAPER);
        }
    }
    return status;
}
GX_WINDOW_PROPERTIES w_bg_splash_properties =
{
    GX_PIXELMAP_ID_BG                        /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES w_bg_splash_w_splash_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PROMPT_PROPERTIES w_bg_splash_txt_version_properties =
{
    GX_STRING_ID_VERSION,                    /* string id                      */
    GX_FONT_ID_SMALL,                        /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_SPRITE_FRAME w_bg_splash_ico_logo_frame_list[26] =
{
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        30,                                  /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        0                                    /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        10                                   /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        20                                   /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        30                                   /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        40                                   /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        50                                   /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        60                                   /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        70                                   /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        80                                   /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        90                                   /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        100                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        110                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        120                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        130                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        140                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        150                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        160                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        170                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        180                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        190                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        200                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        210                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        220                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        230                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        240                                  /* alpha value                    */
    },
    {
        GX_PIXELMAP_ID_ICO_LOGO,             /* pixelmap id                    */
        0,                                   /* x offset                       */
        0,                                   /* y offset                       */
        2,                                   /* frame delay                    */
        GX_SPRITE_BACKGROUND_NO_ACTION,      /* background operation           */
        255                                  /* alpha value                    */
    }
};

GX_SPRITE_PROPERTIES w_bg_splash_ico_logo_properties =
{
    w_bg_splash_ico_logo_frame_list,         /* address of frame list          */
    26,                                      /* frame count                    */
};

GX_CONST GX_STUDIO_WIDGET w_bg_splash_ico_logo_define =
{
    "ico_logo",
    GX_TYPE_SPRITE,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_SPRITE_AUTO,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_SPRITE),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_sprite_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 80, 219, 239},                      /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_SPLASH_CONTROL_BLOCK, w_bg_splash_ico_logo), /* control block */
    (void *) &w_bg_splash_ico_logo_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET w_bg_splash_txt_version_define =
{
    "txt_version",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_RIGHT,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {155, 5, 234, 28},                       /* widget size                    */
    &w_bg_splash_ico_logo_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_SPLASH_CONTROL_BLOCK, w_bg_splash_txt_version), /* control block */
    (void *) &w_bg_splash_txt_version_properties /* extended properties        */
};

GX_CONST GX_STUDIO_WIDGET w_bg_splash_w_splash_define =
{
    "w_splash",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_SELECTED_FILL,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 239, 319},                        /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    &w_bg_splash_txt_version_define,         /* child widget definition        */
    offsetof(W_BG_SPLASH_CONTROL_BLOCK, w_bg_splash_w_splash), /* control block */
    (void *) &w_bg_splash_w_splash_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET w_bg_splash_define =
{
    "w_bg_splash",
    GX_TYPE_WINDOW,                          /* widget type                    */
    ID_WIN_SPLASH,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(W_BG_SPLASH_CONTROL_BLOCK),       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) w_splash_event, /* event function override */
    {0, 0, 239, 319},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &w_bg_splash_w_splash_define,            /* child widget                   */
    0,                                       /* control block                  */
    (void *) &w_bg_splash_properties         /* extended properties            */
};
GX_WINDOW_PROPERTIES w_bg_usb_properties =
{
    GX_PIXELMAP_ID_BG                        /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES w_bg_usb_w_usb_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_ICON_PROPERTIES w_bg_usb_ico_usb_properties =
{
    GX_PIXELMAP_ID_ICO_USB,                  /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES w_bg_usb_txt_usb_1_properties =
{
    GX_STRING_ID_USB_1,                      /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES w_bg_usb_txt_usb_2_properties =
{
    GX_STRING_ID_USB_2,                      /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};

GX_CONST GX_STUDIO_WIDGET w_bg_usb_txt_usb_2_define =
{
    "txt_usb_2",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {10, 230, 229, 259},                     /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_USB_CONTROL_BLOCK, w_bg_usb_txt_usb_2), /* control block     */
    (void *) &w_bg_usb_txt_usb_2_properties  /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET w_bg_usb_txt_usb_1_define =
{
    "txt_usb_1",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {10, 200, 229, 229},                     /* widget size                    */
    &w_bg_usb_txt_usb_2_define,              /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_USB_CONTROL_BLOCK, w_bg_usb_txt_usb_1), /* control block     */
    (void *) &w_bg_usb_txt_usb_1_properties  /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET w_bg_usb_ico_usb_define =
{
    "ico_usb",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {40, 40, 199, 199},                      /* widget size                    */
    &w_bg_usb_txt_usb_1_define,              /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_USB_CONTROL_BLOCK, w_bg_usb_ico_usb), /* control block       */
    (void *) &w_bg_usb_ico_usb_properties    /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET w_bg_usb_w_usb_define =
{
    "w_usb",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_SELECTED_FILL,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 239, 319},                        /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    &w_bg_usb_ico_usb_define,                /* child widget definition        */
    offsetof(W_BG_USB_CONTROL_BLOCK, w_bg_usb_w_usb), /* control block         */
    (void *) &w_bg_usb_w_usb_properties      /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET w_bg_usb_define =
{
    "w_bg_usb",
    GX_TYPE_WINDOW,                          /* widget type                    */
    ID_WIN_USB,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(W_BG_USB_CONTROL_BLOCK),          /* control block size             */
    GX_COLOR_ID_SELECTED_FILL,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) w_usb_event, /* event function override */
    {0, 0, 239, 319},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &w_bg_usb_w_usb_define,                  /* child widget                   */
    0,                                       /* control block                  */
    (void *) &w_bg_usb_properties            /* extended properties            */
};
GX_WINDOW_PROPERTIES w_bg_main_properties =
{
    GX_PIXELMAP_ID_BG                        /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES w_bg_main_w_main_properties =
{
    GX_PIXELMAP_ID_OVERLAY                   /* wallpaper pixelmap id          */
};
GX_PIXELMAP_BUTTON_PROPERTIES w_bg_main_btn_left_properties =
{
    GX_PIXELMAP_ID_BTN_DOWN,                 /* normal pixelmap id             */
    0,                                       /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES w_bg_main_btn_right_properties =
{
    GX_PIXELMAP_ID_BTN_UP,                   /* normal pixelmap id             */
    0,                                       /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PROMPT_PROPERTIES w_bg_main_txt_status_properties =
{
    GX_STRING_ID_STOPPED,                    /* string id                      */
    GX_FONT_ID_SMALL,                        /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES w_bg_main_txt_time_properties =
{
    GX_STRING_ID_BLANK,                      /* string id                      */
    GX_FONT_ID_SMALL,                        /* font id                        */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_VERTICAL_LIST_PROPERTIES w_bg_main_list_files_properties =
{
    0,                                       /* wallpaper id                   */
    list_files_callback,                     /* callback function              */
    5                                        /* total rows                     */
};
GX_PROMPT_PROPERTIES w_bg_main_list_item_0_properties =
{
    GX_STRING_ID_STRING,                     /* string id                      */
    GX_FONT_ID_SMALL,                        /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES w_bg_main_list_item_1_properties =
{
    GX_STRING_ID_STRING,                     /* string id                      */
    GX_FONT_ID_SMALL,                        /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES w_bg_main_list_item_2_properties =
{
    GX_STRING_ID_STRING,                     /* string id                      */
    GX_FONT_ID_SMALL,                        /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES w_bg_main_list_item_3_properties =
{
    GX_STRING_ID_STRING,                     /* string id                      */
    GX_FONT_ID_SMALL,                        /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES w_bg_main_list_item_4_properties =
{
    GX_STRING_ID_STRING,                     /* string id                      */
    GX_FONT_ID_SMALL,                        /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PIXELMAP_BUTTON_PROPERTIES w_bg_main_btn_mid_properties =
{
    GX_PIXELMAP_ID_BTN_CIRCLE,               /* normal pixelmap id             */
    0,                                       /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};
GX_PROGRESS_BAR_INFO w_bg_main_bar_volume_properties =
{
    0,                                       /* mimimun value                  */
    255,                                     /* maximum value                  */
    128,                                     /* current value                  */
    GX_FONT_ID_SYSTEM,                       /* font_id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_PIXELMAP_ID_BAR_VOL                   /* fill pixelmap                  */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_list_item_4_define =
{
    "list_item_4",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_DRAW_SELECTED|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {2, 196, 237, 238},                      /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_list_item_4), /* control block */
    (void *) &w_bg_main_list_item_4_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_list_item_3_define =
{
    "list_item_3",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_DRAW_SELECTED|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {2, 153, 237, 195},                      /* widget size                    */
    &w_bg_main_list_item_4_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_list_item_3), /* control block */
    (void *) &w_bg_main_list_item_3_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_list_item_2_define =
{
    "list_item_2",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_DRAW_SELECTED|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {2, 110, 237, 152},                      /* widget size                    */
    &w_bg_main_list_item_3_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_list_item_2), /* control block */
    (void *) &w_bg_main_list_item_2_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_list_item_1_define =
{
    "list_item_1",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_DRAW_SELECTED|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {2, 67, 237, 109},                       /* widget size                    */
    &w_bg_main_list_item_2_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_list_item_1), /* control block */
    (void *) &w_bg_main_list_item_1_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_list_item_0_define =
{
    "list_item_0",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_DRAW_SELECTED|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {2, 24, 237, 66},                        /* widget size                    */
    &w_bg_main_list_item_1_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_list_item_0), /* control block */
    (void *) &w_bg_main_list_item_0_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_bar_volume_define =
{
    "bar_volume",
    GX_TYPE_PROGRESS_BAR,                    /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT,   /* style flags                */
    0,                                       /* status flags                   */
    sizeof(GX_PROGRESS_BAR),                 /* control block size             */
    GX_COLOR_ID_CANVAS,                      /* normal color id                */
    GX_COLOR_ID_SLIDER_TICK,                 /* selected color id              */
    gx_studio_progress_bar_create,           /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 240, 239, 249},                      /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_bar_volume), /* control block  */
    (void *) &w_bg_main_bar_volume_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_btn_mid_define =
{
    "btn_mid",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_BTN_MID,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {80, 240, 159, 319},                     /* widget size                    */
    &w_bg_main_bar_volume_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_btn_mid), /* control block     */
    (void *) &w_bg_main_btn_mid_properties   /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_list_files_define =
{
    "list_files",
    GX_TYPE_VERTICAL_LIST,                   /* widget type                    */
    ID_LIST_FILES,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_VERTICAL_LIST),                /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_vertical_list_create,          /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {2, 24, 237, 240},                       /* widget size                    */
    &w_bg_main_btn_mid_define,               /* next widget definition         */
    &w_bg_main_list_item_0_define,           /* child widget definition        */
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_list_files), /* control block  */
    (void *) &w_bg_main_list_files_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_txt_time_define =
{
    "txt_time",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_RIGHT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {117, 0, 236, 24},                       /* widget size                    */
    &w_bg_main_list_files_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_txt_time), /* control block    */
    (void *) &w_bg_main_txt_time_properties  /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_txt_status_define =
{
    "txt_status",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {3, 0, 236, 24},                         /* widget size                    */
    &w_bg_main_txt_time_define,              /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_txt_status), /* control block  */
    (void *) &w_bg_main_txt_status_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_btn_right_define =
{
    "btn_right",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_BTN_RIGHT,                            /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {160, 240, 239, 319},                    /* widget size                    */
    &w_bg_main_txt_status_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_btn_right), /* control block   */
    (void *) &w_bg_main_btn_right_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_btn_left_define =
{
    "btn_left",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    ID_BTN_LEFT,                             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_BUTTON),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 240, 79, 319},                       /* widget size                    */
    &w_bg_main_btn_right_define,             /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_btn_left), /* control block    */
    (void *) &w_bg_main_btn_left_properties  /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_w_main_define =
{
    "w_main",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_WINDOW),                       /* control block size             */
    GX_COLOR_ID_SELECTED_FILL,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 239, 319},                        /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    &w_bg_main_btn_left_define,              /* child widget definition        */
    offsetof(W_BG_MAIN_CONTROL_BLOCK, w_bg_main_w_main), /* control block      */
    (void *) &w_bg_main_w_main_properties    /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET w_bg_main_define =
{
    "w_bg_main",
    GX_TYPE_WINDOW,                          /* widget type                    */
    ID_WIN_MAIN,                             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(W_BG_MAIN_CONTROL_BLOCK),         /* control block size             */
    GX_COLOR_ID_SELECTED_FILL,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) w_main_event, /* event function override */
    {0, 0, 239, 319},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &w_bg_main_w_main_define,                /* child widget                   */
    0,                                       /* control block                  */
    (void *) &w_bg_main_properties           /* extended properties            */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY audio_player_widget_table[] =
{
    { &w_bg_splash_define, (GX_WIDGET *) &w_bg_splash },
    { &w_bg_usb_define, (GX_WIDGET *) &w_bg_usb },
    { &w_bg_main_define, (GX_WIDGET *) &w_bg_main },
    {GX_NULL, GX_NULL}
};

static GX_WIDGET *gx_studio_nested_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
    UINT status = GX_SUCCESS;
    GX_WIDGET *widget = GX_NULL;
    GX_VALUE   list_count = 0;
    GX_VALUE   list_total_count = 0;

    if(parent && (parent->gx_widget_type == GX_TYPE_MENU))
    {
        list_total_count = ((GX_MENU *)parent)->gx_menu_list_total_count;
    }

    while(definition && status == GX_SUCCESS)
    {
        if (definition->create_function)
        {
            if (definition->style & GX_STYLE_DYNAMICALLY_ALLOCATED)
            {
                status = gx_widget_allocate(&widget, definition->control_block_size);
                if (status != GX_SUCCESS)
                {
                    return GX_NULL;
                }
            }
            else
            {
                if (control == GX_NULL)
                {
                    return GX_NULL;
                }
                widget = (GX_WIDGET *) (control + definition->control_block_offset);
            }

            status = definition->create_function(definition, widget, parent);

            if(list_count < list_total_count)
            {
                gx_menu_insert((GX_MENU *)parent, widget);
                list_count++;
            }

            if (status == GX_SUCCESS)
            {
                if (definition->widget_type != GX_TYPE_TEMPLATE)
                {
                    gx_widget_fill_color_set(widget, definition->normal_fill_color_id, definition->selected_fill_color_id);
                }

                if (!(definition->status & GX_STATUS_ACCEPTS_FOCUS))
                {
                    gx_widget_status_remove(widget, GX_STATUS_ACCEPTS_FOCUS);
                }

                if (definition->draw_function)
                {
                    gx_widget_draw_set(widget, definition->draw_function);
                }
                if (definition->event_function)
                {
                    gx_widget_event_process_set(widget, definition->event_function);
                }

                #if defined(GX_WIDGET_USER_DATA)
                widget->gx_widget_user_data = definition->user_data;
                #endif

                if (definition->child_widget)
                {
                    gx_studio_nested_widget_create(control, definition->child_widget, widget);
                }
            }
            definition = definition->next_widget;
        }
    }
    return widget;
}

GX_WIDGET *gx_studio_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
    GX_WIDGET *widget;
    widget = gx_studio_nested_widget_create(control, definition, GX_NULL);

    if (parent && widget)
    {
        gx_widget_attach(parent, widget);
    }
    return widget;
}

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget)
{
    UINT status = GX_FAILURE;
    GX_CONST GX_STUDIO_WIDGET_ENTRY *entry = audio_player_widget_table;
    GX_WIDGET *widget = GX_NULL;

    while(entry->widget_information)
    {
        if (!strcmp(name, entry->widget_information->widget_name))
        {
            widget = gx_studio_widget_create((GX_BYTE *) entry->widget, entry->widget_information, parent);
            if (widget)
            {
                status = GX_SUCCESS;
            }
            break;
        }
        entry++;
    }

    if (new_widget)
    {
        *new_widget = widget;
    }
    return status;
}

extern GX_CONST GX_THEME *display_1_theme_table[];
extern GX_CONST GX_CHAR **display_1_language_table[];

GX_STUDIO_DISPLAY_INFO audio_player_display_table[1] =
{
    {
    "display_1",
    "display_1_canvas",
    display_1_theme_table,
    display_1_language_table,
    DISPLAY_1_THEME_TABLE_SIZE,
    DISPLAY_1_LANGUAGE_TABLE_SIZE,
    DISPLAY_1_STRING_TABLE_SIZE,
    256,                                     /* x resolution                   */
    320,                                     /* y resolution                   */
    &display_1_control_block,
    &display_1_canvas_control_block,
    &display_1_root_window,
    GX_NULL,                                 /* canvas memory area             */
    163840                                   /* canvas memory size in bytes    */
    }
};

UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
    USHORT language, USHORT theme, GX_WINDOW_ROOT **return_root)
{
    GX_CONST GX_THEME *theme_ptr;
    GX_RECTANGLE size;

    GX_STUDIO_DISPLAY_INFO *display_info = &audio_player_display_table[display];


/* create the requested display                                                */

    gx_display_create(display_info->display,
                      display_info->name,
                      driver,
                      (GX_VALUE) display_info->x_resolution,
                      (GX_VALUE) display_info->y_resolution);


/* install the request theme                                                   */

    if(display_info->theme_table)
    {
        theme_ptr = display_info->theme_table[theme];
        if(theme_ptr)
        {
            gx_display_color_table_set(display_info->display, theme_ptr->theme_color_table, theme_ptr->theme_color_table_size);
            
/* install the color palette if required                                       */
            if (display_info->display->gx_display_driver_palette_set &&
                theme_ptr->theme_palette != NULL)
            {
                display_info->display->gx_display_driver_palette_set(display_info->display, theme_ptr->theme_palette, theme_ptr->theme_palette_size);
            }

            gx_display_font_table_set(display_info->display, theme_ptr->theme_font_table, theme_ptr->theme_font_table_size);
            gx_display_pixelmap_table_set(display_info->display, theme_ptr->theme_pixelmap_table, theme_ptr->theme_pixelmap_table_size);
            gx_system_scroll_appearance_set(theme_ptr->theme_vertical_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_vertical_scrollbar_appearance);
            gx_system_scroll_appearance_set(theme_ptr->theme_horizontal_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_horizontal_scrollbar_appearance);
            gx_system_language_table_set((GX_CHAR ***) display_info->language_table, display_info->language_table_size, display_info->string_table_size);
            gx_system_active_language_set(language);
        }
    }


/* create the canvas for this display                                          */

    gx_canvas_create(display_info->canvas,
                     display_info->canvas_name,
                     display_info->display,
                     GX_CANVAS_MANAGED | GX_CANVAS_VISIBLE,
                     display_info->x_resolution,
                     display_info->y_resolution,
                     display_info->canvas_memory,
                     display_info->canvas_memory_size);

/* Create the root window for this canvas                                      */

    gx_utility_rectangle_define(&size,
                                0, 0,
                                (GX_VALUE) (display_info->x_resolution - 1),
                                (GX_VALUE) (display_info->y_resolution - 1));

    gx_window_root_create(display_info->root_window,
                          display_info->name,
                          display_info->canvas, GX_STYLE_NONE, 0, &size);
    if (return_root)
    {
        *return_root = display_info->root_window;
    }
    return GX_SUCCESS;
}

/* Provide display driver setup function                                       */

#if defined(GX_TARGET_WIN32) || defined(GX_TARGET_LINUX)

UINT _gx_synergy_display_driver_setup(GX_DISPLAY *display)
{
    win32_synergy_graphics_driver_setup_565rgb(display);
    return GX_SUCCESS;
}
#else
UINT _gx_synergy_display_driver_setup(GX_DISPLAY *display)
{
    _gx_display_driver_565rgb_setup(display, GX_NULL, _gx_dave2d_buffer_toggle);
    display->gx_display_handle =    0;
    display -> gx_display_driver_horizontal_pattern_line_draw  = _gx_dave2d_horizontal_pattern_line_draw_565;
    display -> gx_display_driver_vertical_pattern_line_draw    = _gx_dave2d_vertical_pattern_line_draw_565;
    display -> gx_display_driver_pixel_write                   = _gx_dave2d_pixel_write_565;
    display -> gx_display_driver_pixel_blend                   = _gx_dave2d_pixel_blend_565;
    display -> gx_display_driver_pixelmap_rotate               = _gx_dave2d_pixelmap_rotate_16bpp;
    display -> gx_display_driver_drawing_initiate              = _gx_dave2d_drawing_initiate;
    display -> gx_display_driver_drawing_complete              = _gx_dave2d_drawing_complete;
    display -> gx_display_driver_canvas_copy                   = _gx_dave2d_canvas_copy;
    display -> gx_display_driver_canvas_blend                  = _gx_dave2d_canvas_blend;
    display -> gx_display_driver_simple_line_draw              = _gx_dave2d_simple_line_draw;
    display -> gx_display_driver_horizontal_line_draw          = _gx_dave2d_horizontal_line;
    display -> gx_display_driver_vertical_line_draw            = _gx_dave2d_vertical_line;
    display -> gx_display_driver_polygon_draw                  = _gx_dave2d_polygon_draw;
    display -> gx_display_driver_polygon_fill                  = _gx_dave2d_polygon_fill;
    display -> gx_display_driver_block_move                    = _gx_dave2d_block_move;
    display -> gx_display_driver_pixelmap_draw                 = _gx_dave2d_pixelmap_draw;
    display -> gx_display_driver_horizontal_pixelmap_line_draw = _gx_dave2d_horizontal_pixelmap_line_draw;
    display -> gx_display_driver_alphamap_draw                 = _gx_dave2d_alphamap_draw;
    display -> gx_display_driver_simple_wide_line_draw         = _gx_dave2d_simple_wide_line;
    display -> gx_display_driver_anti_aliased_line_draw        = _gx_dave2d_aliased_line;
    display -> gx_display_driver_anti_aliased_wide_line_draw   = _gx_dave2d_aliased_wide_line;
    display -> gx_display_driver_pixelmap_blend                = _gx_dave2d_pixelmap_blend;
    display -> gx_display_driver_8bit_glyph_draw               = _gx_dave2d_raw_glyph_8bit_draw;
    display -> gx_display_driver_4bit_glyph_draw               = _gx_dave2d_raw_glyph_4bit_draw;
    display -> gx_display_driver_1bit_glyph_draw               = _gx_dave2d_raw_glyph_1bit_draw;
    display -> gx_display_driver_8bit_compressed_glyph_draw    = _gx_dave2d_compressed_glyph_8bit_draw;
    display -> gx_display_driver_4bit_compressed_glyph_draw    = _gx_dave2d_compressed_glyph_4bit_draw;
    display -> gx_display_driver_1bit_compressed_glyph_draw    = _gx_dave2d_compressed_glyph_1bit_draw;
    #if defined(GX_ARC_DRAWING_SUPPORT)
    display -> gx_display_driver_anti_aliased_circle_draw      = _gx_dave2d_aliased_circle_draw;
    display -> gx_display_driver_anti_aliased_wide_circle_draw = _gx_dave2d_aliased_circle_draw;
    display -> gx_display_driver_circle_draw                   = _gx_dave2d_circle_draw;
    display -> gx_display_driver_circle_fill                   = _gx_dave2d_circle_fill;
    display -> gx_display_driver_pie_fill                      = _gx_dave2d_pie_fill;
    display -> gx_display_driver_anti_aliased_arc_draw         = _gx_dave2d_aliased_arc_draw;
    display -> gx_display_driver_arc_draw                      = _gx_dave2d_arc_draw;
    display -> gx_display_driver_arc_fill                      = _gx_dave2d_arc_fill;
    display -> gx_display_driver_anti_aliased_ellipse_draw     = _gx_dave2d_aliased_ellipse_draw;
    display -> gx_display_driver_ellipse_draw                  = _gx_dave2d_ellipse_draw;
    display -> gx_display_driver_ellipse_fill                  = _gx_dave2d_ellipse_fill;
    display -> gx_display_driver_wide_circle_draw              = _gx_dave2d_circle_draw;
    display -> gx_display_driver_anti_aliased_wide_arc_draw    = _gx_dave2d_aliased_arc_draw;
    display -> gx_display_driver_wide_arc_draw                 = _gx_dave2d_arc_draw;
    #endif
    return GX_SUCCESS;
}
#endif
#undef GUIX_STUDIO_GENERATED_FILE
